<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.9" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>
</Project>
