<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <OutputType>Exe</OutputType>

    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <Title>Dotnet Cleanup</Title>
    <AssemblyName>cleanup</AssemblyName>
    <PackageId>cleanup</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <Version>0.7.0</Version>

    <ToolCommandName>cleanup</ToolCommandName>
    <PackAsTool>True</PackAsTool>
    <PackageOutputPath>./nupkg</PackageOutputPath>

    <PackageProjectUrl>https://github.com/sebnilsson/DotnetGuid</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <Authors>Sebastian Nilsson</Authors>
    <Description>.NET Global Tool for cleaning up build output and dependency folders.</Description>
    <Summary>.NET Global Tool for cleaning up build output and dependency folders.</Summary>

    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.49.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotNetCleanup.Tests" />
    <InternalsVisibleTo Include="DotnetCleanup.IntegrationTests" />
  </ItemGroup>

</Project>
