<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <OutputType>Exe</OutputType>

    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <Title>Dotnet Cleanup</Title>
    <AssemblyName>cleanup</AssemblyName>
    <PackageId>cleanup</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <Version>0.7.0</Version>

    <ToolCommandName>cleanup</ToolCommandName>
    <PackAsTool>True</PackAsTool>
    <PackageOutputPath>./nupkg</PackageOutputPath>

    <PackageProjectUrl>https://github.com/sebnilsson/DotnetGuid</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <Authors>Sebastian Nilsson</Authors>
    <Description>.NET Core Global Tool for cleaning up solution, project or folder</Description>
    <Summary>.NET Core Global Tool for cleaning up solution, project or folder</Summary>

    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CommandContextAppFactory.cs" />
    <Compile Remove="EnumerableExtensions.cs" />
    <Compile Remove="Events\CleanupPathsNoFiles.cs" />
    <Compile Remove="ITraceWriter.cs" />
    <Compile Remove="TraceWriter.cs" />
    <Compile Remove="TraceWriterExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KeyLocks" Version="0.8.0" />
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="2.3.4" />
    <PackageReference Include="MediatR" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
  </ItemGroup>

</Project>
