# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Docker Info
      run: docker version && docker info

    - name: .NET Restore
      run: dotnet restore

    - name: .NET Build
      run: dotnet build --no-restore --configuration Release

    - name: .NET Test
      run: dotnet test --no-restore --no-build --configuration Release --verbosity minimal --logger trx --results-directory TestResults

    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**/*.trx
        if-no-files-found: ignore
